# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HerdrServe < Formula
  desc "Opt-in phone UI — live terminal relay for Herder agents"
  homepage "https://github.com/Blankeos/herdr-serve"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Blankeos/herdr-serve/releases/download/v0.0.1/herdr-serve-x86_64-apple-darwin.tar.xz"
      sha256 "5b03f8f06d64edc7050fbdc55b11ac6dd2d78e8a821a7acc143986239f7ec890"

      define_method(:install) do
        bin.install "herdr-serve"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Blankeos/herdr-serve/releases/download/v0.0.1/herdr-serve-aarch64-apple-darwin.tar.xz"
      sha256 "8a160c48e7771977a46e06b405a1ab197986e84fed601a1f99355411f61ac9b3"

      define_method(:install) do
        bin.install "herdr-serve"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Blankeos/herdr-serve/releases/download/v0.0.1/herdr-serve-x86_64-unknown-linux-gnu.tar.xz"
      sha256 "937edb8100f155d27067e852ff744cdbe7d08e0a8a51405fbc3eb3900426823d"
      define_method(:install) do
        bin.install "herdr-serve"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Blankeos/herdr-serve/releases/download/v0.0.1/herdr-serve-aarch64-unknown-linux-gnu.tar.xz"
      sha256 "04146f5bd49213b80e2c95f95c9e2d20873008238879d2348068f329b40a0173"
      define_method(:install) do
        bin.install "herdr-serve"
      end
    end
  end

  test do
    system "#{bin}/herdr-serve", "version"
  end
end
